// -----------------------------------------------------------------------------
// Testbench for the Muffin-instrumented and2.
//
// The DUT is *not* the and2.v sitting next to this file: it is the version
// regenerated by hif2verilog after Muffin instrumented it, which carries one
// extra port, muffinMutPort. Driving that port selects which fault is active:
//
//   muffinMutPort = 0  -> golden, no fault
//   muffinMutPort = 1  -> fault 1, y stuck-at-0
//   muffinMutPort = 2  -> fault 2, y stuck-at-1
//
// The golden reference is computed here directly (golden_y = a & b), so every
// vector shows the faulty output next to what the fault-free circuit would
// have produced.
// -----------------------------------------------------------------------------

`timescale 1ns / 1ps

module tb;

    reg a;
    reg b;
    reg [31:0] muffinMutPort;

    wire y;

    // What and2 did before instrumentation. This is the reference every
    // vector is compared against.
    wire golden_y = a & b;

    integer errors;

    and2 dut (
        .a(a),
        .b(b),
        .y(y),
        .muffinMutPort(muffinMutPort)
    );

    // Select which fault is active.
    //
    // Muffin instruments the design by rewriting the expression driving y, but
    // muffinMutPort is not added to the sensitivity list of the always block:
    // changing it alone does not re-evaluate y. Poke the inputs so the next
    // vector starts from a settled state.
    task select_fault;
        input [31:0] id;
        begin
            muffinMutPort = id;
            a = ~a;
            #1;
            a = ~a;
            #1;
        end
    endtask

    // Apply one input vector and compare the instrumented output against both
    // the golden circuit and what the active fault is expected to force.
    task check;
        input ai;
        input bi;
        input expected;
        begin
            a = ai;
            b = bi;
            #1;
            // Two separate $display calls rather than one with a conditional
            // suffix: Verilog pads the shorter arm of a string ternary, which
            // would leave trailing blanks on every non-detecting line.
            if (y !== golden_y) begin
                $display("  a=%b b=%b  golden=%b  dut=%b   %s   <-- fault detected",
                         a, b, golden_y, y, (y === expected) ? "PASS" : "FAIL");
            end else begin
                $display("  a=%b b=%b  golden=%b  dut=%b   %s",
                         a, b, golden_y, y, (y === expected) ? "PASS" : "FAIL");
            end
            if (y !== expected) begin
                errors = errors + 1;
            end
        end
    endtask

    initial begin
        errors = 0;

        // --- muffinMutPort = 0: the design must behave exactly as written ---
        $display("");
        $display("=== Golden: muffinMutPort = 0 (no fault active) ===");
        select_fault(0);
        check(0, 0, 1'b0);
        check(0, 1, 1'b0);
        check(1, 0, 1'b0);
        check(1, 1, 1'b1);

        // --- muffinMutPort = 1: y forced to 0 -------------------------------
        // Only a=1,b=1 distinguishes this from the golden circuit: it is the
        // single input vector whose fault-free output is 1.
        $display("");
        $display("=== Fault 1: y stuck-at-0 (muffinMutPort = 1) ===");
        select_fault(1);
        check(0, 0, 1'b0);
        check(0, 1, 1'b0);
        check(1, 0, 1'b0);
        check(1, 1, 1'b0);

        // --- muffinMutPort = 2: y forced to 1 -------------------------------
        // The mirror image: every vector except a=1,b=1 detects this fault,
        // because those are the three vectors whose fault-free output is 0.
        $display("");
        $display("=== Fault 2: y stuck-at-1 (muffinMutPort = 2) ===");
        select_fault(2);
        check(0, 0, 1'b1);
        check(0, 1, 1'b1);
        check(1, 0, 1'b1);
        check(1, 1, 1'b1);

        $display("");
        if (errors == 0) begin
            $display("RESULT: PASS - golden matches a & b, fault 1 behaves as y stuck-at-0, fault 2 as y stuck-at-1.");
            $display("");
            $finish;
        end else begin
            $display("RESULT: FAIL - %0d vector(s) did not behave as expected.", errors);
            $display("");
            $fatal(1);
        end
    end

endmodule
