// -----------------------------------------------------------------------------
// Testbench for the Muffin-instrumented and2.
//
// The DUT is *not* the and2.v sitting next to this file: it is the version
// regenerated by hif2verilog after Muffin instrumented it, which carries one
// extra port, muffinMutPort. Driving that port selects which fault is active:
//
//   muffinMutPort = 0  -> golden, no fault
//   muffinMutPort = 1  -> fault 1, y stuck-at-0
//   muffinMutPort = 2  -> fault 2, y stuck-at-1
//
// The golden reference is computed here directly (golden_y = a & b), so every
// vector shows the faulty output next to what the fault-free circuit would
// have produced.
// -----------------------------------------------------------------------------

`timescale 1ns / 1ps

module tb;

    reg a;
    reg b;
    reg [31:0] muffinMutPort;

    wire y;

    // What and2 did before instrumentation. This is the reference every
    // vector is compared against.
    wire golden_y = a & b;

    integer errors;

    and2 dut (
        .a(a),
        .b(b),
        .y(y),
        .muffinMutPort(muffinMutPort)
    );

    // Select which fault is active. Changing muffinMutPort is all it takes:
    // the instrumented always block is sensitive to it, so y re-evaluates
    // immediately without the inputs having to move.
    task select_fault;
        input [31:0] id;
        begin
            muffinMutPort = id;
            #1;
        end
    endtask

    // Apply one input vector and compare the instrumented output against both
    // the golden circuit and what the active fault is expected to force.
    task check;
        input ai;
        input bi;
        input expected;
        begin
            a = ai;
            b = bi;
            #1;
            // Two separate $display calls rather than one with a conditional
            // suffix: Verilog pads the shorter arm of a string ternary, which
            // would leave trailing blanks on every non-detecting line.
            if (y !== golden_y) begin
                $display("  a=%b b=%b  golden=%b  dut=%b   %s   <-- fault detected",
                         a, b, golden_y, y, (y === expected) ? "PASS" : "FAIL");
            end else begin
                $display("  a=%b b=%b  golden=%b  dut=%b   %s",
                         a, b, golden_y, y, (y === expected) ? "PASS" : "FAIL");
            end
            if (y !== expected) begin
                errors = errors + 1;
            end
        end
    endtask

    // Change only muffinMutPort and report what y does, without touching the
    // inputs at all.
    task live_check;
        input [31:0] id;
        input expected;
        input [8*34:1] label;
        begin
            muffinMutPort = id;
            #1;
            $display("  mut=%0d  a=%b b=%b  y=%b   %s   %0s",
                     id, a, b, y, (y === expected) ? "PASS" : "FAIL", label);
            if (y !== expected) begin
                errors = errors + 1;
            end
        end
    endtask

    initial begin
        errors = 0;

        // --- muffinMutPort = 0: the design must behave exactly as written ---
        $display("");
        $display("=== Golden: muffinMutPort = 0 (no fault active) ===");
        select_fault(0);
        check(0, 0, 1'b0);
        check(0, 1, 1'b0);
        check(1, 0, 1'b0);
        check(1, 1, 1'b1);

        // --- muffinMutPort = 1: y forced to 0 -------------------------------
        // Only a=1,b=1 distinguishes this from the golden circuit: it is the
        // single input vector whose fault-free output is 1.
        $display("");
        $display("=== Fault 1: y stuck-at-0 (muffinMutPort = 1) ===");
        select_fault(1);
        check(0, 0, 1'b0);
        check(0, 1, 1'b0);
        check(1, 0, 1'b0);
        check(1, 1, 1'b0);

        // --- muffinMutPort = 2: y forced to 1 -------------------------------
        // The mirror image: every vector except a=1,b=1 detects this fault,
        // because those are the three vectors whose fault-free output is 0.
        $display("");
        $display("=== Fault 2: y stuck-at-1 (muffinMutPort = 2) ===");
        select_fault(2);
        check(0, 0, 1'b1);
        check(0, 1, 1'b1);
        check(1, 0, 1'b1);
        check(1, 1, 1'b1);

        // --- The port is live: no stimulus needed to switch faults ----------
        // Everything above re-applies the four input vectors after selecting
        // each fault, which is what a real campaign does. This last section
        // shows that re-applying them is not what makes the fault take effect:
        // a and b are pinned at 1 and never touched again, and only
        // muffinMutPort moves.
        $display("");
        $display("=== Switching faults with the inputs held still (a=1, b=1) ===");
        a = 1'b1;
        b = 1'b1;
        #1;
        live_check(0, 1'b1, "golden");
        live_check(1, 1'b0, "fault 1 active   <-- y forced low");
        live_check(0, 1'b1, "cleared          <-- golden again");
        live_check(2, 1'b1, "fault 2 active");
        live_check(0, 1'b1, "cleared");

        $display("");
        if (errors == 0) begin
            $display("RESULT: PASS - golden matches a & b, fault 1 behaves as y stuck-at-0, fault 2 as y stuck-at-1.");
            $display("");
            $finish;
        end else begin
            $display("RESULT: FAIL - %0d vector(s) did not behave as expected.", errors);
            $display("");
            $fatal(1);
        end
    end

endmodule
